import { chromium } from 'playwright';
const F = 'file:///Users/paolo/stardust/2026-08/mdanderson/stardust/prototypes/horizon-proposed.html';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto(F, { waitUntil: 'networkidle', timeout: 60000 }).catch(()=>{});
await p.waitForTimeout(1800);
await p.screenshot({ path: '.impeccable/review/crop-hero.png' });
await p.click('#burger'); await p.waitForTimeout(700);
await p.screenshot({ path: '.impeccable/review/crop-canopy.png' });
await b.close(); console.log('ok');
