import { chromium } from 'playwright';
const F = 'file:///Users/paolo/stardust/2026-08/mdanderson/stardust/prototypes/horizon-proposed.html';
const b = await chromium.launch();
const d = await b.newPage({ viewport: { width: 1440, height: 900 } });
await d.goto(F, { waitUntil: 'networkidle', timeout: 60000 }).catch(()=>{});
await d.waitForTimeout(1500);
await d.screenshot({ path: '.impeccable/review/desktop.png', fullPage: true });
await d.click('#burger'); await d.waitForTimeout(600);
await d.screenshot({ path: '.impeccable/review/desktop-canopy.png' });
const m = await b.newPage({ viewport: { width: 390, height: 844 } });
await m.goto(F, { waitUntil: 'networkidle', timeout: 60000 }).catch(()=>{});
await m.waitForTimeout(1200);
await m.screenshot({ path: '.impeccable/review/mobile.png', fullPage: true });
await m.click('#burger'); await m.waitForTimeout(600);
await m.screenshot({ path: '.impeccable/review/mobile-canopy.png' });
const t = await b.newPage({ viewport: { width: 360, height: 800 } });
await t.goto(F, { waitUntil: 'networkidle', timeout: 60000 }).catch(()=>{});
await t.waitForTimeout(800);
const ov = await t.evaluate(() => ({ sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth }));
console.log('360px overflow probe:', JSON.stringify(ov));
await b.close();
